### PR TITLE
Update Scott's RootBeer library Jitpack dependency.

### LINKED ISSUE #7: Could not find com.github.scottyab:rootbeer:1a87fc43254349a7bfe72a8e57e8aa2662f07130
I've been using this plugin in an app for years now, but suddenly the Android build started failing with this error:

Captura de Tela 2022-10-14 às 10 50 41

I've done a quick analysis and realized that the [original Scott's RootBeer library](https://github.com/scottyab/rootbeer) commit referenced in the `build-extras.gradle` by the plugin references a commit that apparently doesn't exist anymore in Jitpack.
```Groovy
repositories{
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile 'com.github.scottyab:rootbeer:1a87fc43254349a7bfe72a8e57e8aa2662f07130'
}
```
As a temporary fix, I swapped the commit in `build-extras.gradle` for the most recent commit, which can be still be found on Jitpack. In the end, the `build-extras.gradle` file stayed like this:
```Groovy
repositories{
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile 'com.github.scottyab:rootbeer:091a157959'
}
```

Honestly, I haven't checked if there's any breaking changes between these commits, but it got my Android build working again, so I'll stick with that for now.

I'll keep this issue here for anyone who has the same trouble, but I plan of adding a PR to fix this, eventually.

### PR DESCRIPTION
**Pull request by CaioMelo8**
Fix #7 by updating the referenced commit hash for Scott's RootBeer library on Jitpack.

### CODE REVIEW

**Comment by karandpr** [comment]
@CaioMelo8 . Thank you for the PR. Appreciate it. 

Jitpack has removed the artifacts for the code I targeted. There was some reason I chose the commit but I cant remember. 

Looks like you have mapped it to commit corresponding to 0.0.8. That should work IMO. Can you change the gradle code to 
`compile 'com.github.scottyab:rootbeer:0.0.8'`

and see if it builds. It just looks cleaner IMO. 
Otherwise, I will just merge the commit

**Comment by CaioMelo8** [comment]
Hi @karandpr, thanks for reviewing the PR!

I agree that it's indeed cleaner, so I updated the gradle configuration to reference the 0.0.8 release. I've updated our project after this change and the Android app build is working fine. I've also ran through our root detection tests and everything seems in order.

**Comment by karandpr** [comment]
@CaioMelo8 
Thank you for the PR. Commit Merged 🍡 .

**Comment by karandpr** [comment]
@CaioMelo8 Pushed to npm registry. Thanks !

**Comment by CaioMelo8** [comment]
@karandpr Great work! Thank you very much!

**Pull request merged**
